# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.1
pipelines:
  custom:
    staging: #name of this pipeline

      - step:
          name: Build
          script:
            - npm install
          artifacts:
            - build/**
      - step:
          name: Deploy to S3
          deployment: staging
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            - npm install -g @angular/cli@7.1.3
            - npm run build
            - ls -ltr
            - cd build
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-south-1'
                S3_BUCKET: 'bibucket-pipeline-code-deploy'
                LOCAL_PATH: $(pwd)
      - step:
          name: Invalidate Cloudfront Cache
          script:
               variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $STAGING_DISTRIBUTION_ID