version: 0.2
env:
  variables:
      key: value
frontend:
  phases:
    preBuild:
      commands:
        - cd react-app
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    files:
       -"**/*"
    discard-paths: no
    baseDirectory: build